services:
  - type: web
    name: tradworld
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DEEPL_API_KEY
        sync: false
